name = "productdevbook-deployment"
type = "javascript"
account_id = "6c91d813234b6a089b08ea197cdafc20"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-07"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = ""
upload.format = "service-worker"